/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WomensRouteImport } from './routes/womens'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MensRouteImport } from './routes/mens'
import { Route as KidsRouteImport } from './routes/kids'
import { Route as IndexRouteImport } from './routes/index'

const WomensRoute = WomensRouteImport.update({
  id: '/womens',
  path: '/womens',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MensRoute = MensRouteImport.update({
  id: '/mens',
  path: '/mens',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsRoute = KidsRouteImport.update({
  id: '/kids',
  path: '/kids',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kids': typeof KidsRoute
  '/mens': typeof MensRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/womens': typeof WomensRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kids': typeof KidsRoute
  '/mens': typeof MensRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/womens': typeof WomensRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kids': typeof KidsRoute
  '/mens': typeof MensRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/womens': typeof WomensRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kids' | '/mens' | '/sitemap.xml' | '/womens'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kids' | '/mens' | '/sitemap.xml' | '/womens'
  id: '__root__' | '/' | '/kids' | '/mens' | '/sitemap.xml' | '/womens'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KidsRoute: typeof KidsRoute
  MensRoute: typeof MensRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WomensRoute: typeof WomensRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/womens': {
      id: '/womens'
      path: '/womens'
      fullPath: '/womens'
      preLoaderRoute: typeof WomensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mens': {
      id: '/mens'
      path: '/mens'
      fullPath: '/mens'
      preLoaderRoute: typeof MensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids': {
      id: '/kids'
      path: '/kids'
      fullPath: '/kids'
      preLoaderRoute: typeof KidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KidsRoute: KidsRoute,
  MensRoute: MensRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WomensRoute: WomensRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
